# Generated by Django 5.1 on 2024-09-04 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(unique=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('in_process_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason_id', models.IntegerField(blank=True, null=True)),
                ('cancel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_names', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('warehouse_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acquiring_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schema', models.CharField(choices=[('FBO', 'FBO'), ('FBS', 'FBS')], max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozon_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
