# Generated by Django 5.1 on 2024-09-03 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozon_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ozon_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('wildberries_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wildberries_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('yandex_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('yandex_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
